services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.34.0
    container_name: thanos-sidecar
    depends_on:
      - prometheus
    volumes:
      - ./thanos/bucket.yml:/etc/thanos/bucket.yml
      - prom_data:/prometheus
    command:
      - sidecar
      - --tsdb.path=/prometheus
      - --prometheus.url=http://prometheus:9090
      - --objstore.config-file=/etc/thanos/bucket.yml
    ports:
      - "10902:10902"

  thanos-store:
    image: quay.io/thanos/thanos:v0.34.0
    container_name: thanos-store
    volumes:
      - ./thanos/bucket.yml:/etc/thanos/bucket.yml
    command:
      - store
      - --objstore.config-file=/etc/thanos/bucket.yml
    ports:
      - "10901:10901"

  thanos-query:
    image: quay.io/thanos/thanos:v0.34.0
    container_name: thanos-query
    depends_on:
      - thanos-store
      - thanos-sidecar
    command:
      - query
      - --store=thanos-store:10901
      - --store=thanos-sidecar:10902
    ports:
      - "9091:9090"

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
volumes:
  prom_data:
  minio_data:
